Kitware/glance

Sources/layouts/Layout2D.js

Slider shows/hides properly when active source changes. Before, the slider would not show up when focusing a 2D view and then loading the first source.
Show nicer corner annotations when there is no active source.

Layout2d fixes

---

Sources/index.js
Sources/ui/MobileOverlay/Overlay.mcss
Sources/ui/MobileOverlay/index.js
Sources/ui/index.js

A quick solution to #40. The long-term solution would be to make Glance mobile-friendly.

fix(MobileOverlay): Add overlay if screen is detected as too small

---

Sources/MainView.js
Sources/RemoteControl.js
Sources/index.js

Fixes regression where the MobileOverlay HOC prevents access to the
underlying MainView instance. This is a general solution to wrapping the
MainView with HOCs.

fix(MainView): Use a remote control for triggering events on MainView

---

package-lock.json
package.json

Update itk.js to 9.1.1, which contains a fix for reading many file formats.
@aylward @jourdain @floryst @agirault annoying ImageIO bug has been addressed! :fireworks: Now we can load all that MetaImage goodness :-).
Testing locally.

fix(ImageIO): Fix loading MetaImage, Nifti, HDF5, MINC

---

src/components/core/App/script.js
src/components/core/App/template.html

Clicking the logo will return to landing page, and a button will pop up allowing you to return to the app from the landing page.
I'm thinking of also adding browser history hooks so back/forward works for this as well.
@agirault

Allow returning to landing page

---

src/components/core/VtkView/script.js

view.setContainer() unbinds the vtkjs mouseup listener, causing "sticky"
widget interaction.
Fixes #114

fix(VtkView): Do not set view container on update

---

src/components/controls/Information/PolyData/template.html

Partially addresses #144. The FPS monitor requires a vtk.js change.
This uses commas for now to avoid text wrap, as the used spaces are not non-breaking.

Use comma as thousands separator

---

externals/Workbox/serviceWorker.js

stale-while-revalidate won't immediately update a resource.

fix(workbox): Use Network-First caching strategy

---

package-lock.json
package.json

The previous commit should have been a fix(), but I typed "chore".

fix(package.json): Upgrade mousetrap and force a new release

---

src/components/controls/ColorBy/script.js

Reference bug: https://discourse.vtk.org/t/paraview-glance-no-color-mapping-when-data-array-name-contains-colon/2022
@jourdain

fix(ColorBy): Use workaround for array names with single colons

---

externals/ITKReader/index.js

Corresponding issue: https://discourse.paraview.org/t/paraview-glance-cannot-load-dcm-files-error-could-not-read-file-work-x-dcm/3342

fix(ITKReader): Dicom should be downloaded as binary

---

src/app.js
src/components/core/BrowserIssues/script.js
src/components/core/BrowserIssues/template.html
src/components/core/Datasets/script.js
src/components/core/GlobalSettings/script.js
src/components/core/GlobalSettings/template.html
src/settings.js
src/store/index.js
src/utils.js

This adds a settings module, which provides persistent settings that is specific to each user's browser.
This also adds `Glance.setSetting(name, value)` and `Glance.getSetting(name)` to the external API. In addition, there is a new setting `collapseDatasetPanels`, which toggles whether the dataset panel defaults to collapsed or not at startup.

Sync settings with store

---

.gitattributes
prettier.config.js

Enforces LF endings when linting for this repo, and tell git to checkout using LF line endings. Should fix #299

chore: Enforce LF line endings in the repo

---

src/store/fileLoader.js

for xxx.nii.gz, macOS recognize it's extension name as `gz` instead of `nii.gz`

fix: can't choose nii.gz on macOS

---

src/components/controls/SliceControl/script.js
src/components/core/LayoutView/script.js
src/components/core/VtkView/script.js
src/config/proxy.js
src/config/proxyUI.js
src/vtk/CustomSliceRepresentationProxy/index.js

Fixes #346 
- Opacity is now saved in state files
- Removed extraneous camera reset
- Guard against null source change

Save opacity and don't reset camera on state load

---

.travis.yml
build/travis-release.sh

This will blow away the build-tmp cache, forcing a re-build.

chore(travis): Workaround travis to get green deploys

---

src/components/tools/PaintTool/script.js

The paint widget needs to be placed within the bounds of the image to
avoid extending the bounds unnecessarily.
Fixes #365

fix(PaintTool): Place paint widget in image bounds

---

src/components/tools/CropTool/script.js
src/components/tools/MeasurementTools/tools/ToolTemplate2D.js

Placing widgets in bounds allows for correct computation of scene
bounds.

fix(tools): Place widgets in correct bounds

---

package-lock.json
package.json
src/io/GlanceVtkJsReader.js

Fixes the loading of opacity transfer functions. It seems I forgot a few things...
Also bumps vtk.js for support with Paraview master.

fix(glancevtkjsreader): normalize opacity pwf nodes before adding them

---

package-lock.json
package.json
src/io/GlanceVtkJsReader.js

This includes a small fix necessary for upgrade, because DataAccessHelpers now need to be explicitly registered, or imported.

Bump vtk-js

---

src/components/controls/ColorBy/script.js

Datasets that have an active point or cell scalars will now have their coloring default to those scalars.

feat(ColorBy): Use default scalars for colorBy

---

src/store/fileLoader.js

So we can for example pass an access token to the header like this:
```js
openRemoteFiles([
{
url: "some/url",
name: "somename.ext",
options: {
headers: {
authorization: `Bearer ${accessToken}`,
"content-type": "application/json",
},
},
},
]);
```

feat(fileloader): implement possibility to pass options for loading files remotely

---

src/store/fileLoader.js

An empty `remoteOpts` throws an error when assigning headers. Default remoteOpts to an empty object.
Closes #433.

fix(fileLoader): create empty remoteOpts

---

.github/workflows/publish.yml
CONTRIBUTING.md
README.md
documentation/config.js
documentation/content/doc/index.md
documentation/content/doc/loading_files.md
documentation/content/gallery/index.md
documentation/content/index.pug
package-lock.json
package.json
src/components/core/AboutBox/template.html
src/components/core/Landing/template.html
static/index.html

Renames ParaView Glance to Glance, and preps for renaming the repo from "Glance" to "glance".
FYI @jcfr

chore: rename ParaView Glance to Glance

---

src/components/controls/SliceControl/script.js

Partially addresses #450, restoring the orientation marker.

fix(SliceControl): guard against no min/max domain

---

src/components/tools/PaintTool/script.js

'manipulator' object does not have 'setOrigin'. 'setHandleOrigin' should be used instead.
Fixes #453

fix(painting): Fix painting tool

---

src/components/tools/PaintTool/script.js
src/store/widgets.js

Closes #459 
- Defer applying girder provenance keys until upload for labelmaps
- delete labelmaps from the store

fix(PaintTool): only apply girder keys on upload

---

src/store/fileLoader.js

`return ret` is in the wrong spot, resulting in a for loop that iterates exactly once.

fix(fileLoader): incorrect return location

---

src/components/core/Datasets/script.js
src/components/core/VtkView/constants.js
src/components/core/VtkView/script.js
src/components/core/VtkView/template.html
src/store/views.js
src/utils.js

Move camera in front of volume in 2D and 3D views
getLPSDirections comes from VolView
Use forwardVector and upwardVector instead of axis, orientation, viewUp when moving the camera
Get these info from a basis (3 vec3) in the view store instead of hardcoding it
Replace VIEW_ORIENTATIONS and VIEW_TYPES with variables in the view store
Introduce the notion of master volume in the view store
Closes #463

Add support for camera with LPS mode

---

externals/ITKReader/ITKDicomImageReader.js
package-lock.json
package.json
src/components/core/GirderBox/script.js
src/components/tools/MedianFilter/script.js
src/vtk/ITKHelper/index.js

The median filter depends on itk.js v13 and an older version of ITKHelper, which has been copied in-tree.

fix(itk): downgrade so median filter works

---

src/vtk/CropWidget/index.js

OutlineContextRepresentation should be used for general outline bounding box, which doesn't work well when we want a non axis-aligned bbox.
This fix and commit message come from PR 1222 of vtk.js by @floryst

Use CroppingOutlineRepresentation in CropWidget

---

package-lock.json
package.json

Bump vtk.js to bring [this fix](https://github.com/Kitware/vtk-js/pull/2909) into glance

Bump vtk.js from 28.0.0 to 28.10.2

---

src/components/core/VtkView/constants.js
src/store/views.js
src/utils.js

This avoids redundant code
Replace getLPSDirections with getSparseOrthogonalMatrix
Replace the array of vectors with a matrix

Use the new getSparseOrthogonalMatrix instead of getLPSDirections

---

src/components/core/FileLoader/script.js
src/components/core/FileLoader/template.html
src/components/tools/MeasurementTools/template.html
src/components/tools/PaintTool/template.html
src/girder.js

Hi, when exporting a scene to Glance from ParaView, I want to be able to make the HTML file be isolated from the network, and avoid making any network call to external servers. This patch allows disabling the Girder integration entierly when the `noGirder` URL parameter is set. On ParaView's side, if a checkbox is active when creating the Glance export, the URL parameter `noGirder` will be forced onto the page if it is not set.
Please tell me if you see a better implementation of this idea.
cc @mwestphal

feat(girder): allow disabling girder integration entirely

---

.github/workflows/publish.yml
build/webpack.base.config.js

@bruyeret I realized that we do have references to `ParaViewGlance.html` in the output bundle, so this PR adds that back while preserving the regular bundle.

fix: produce an inline + regular bundle
