Kitware/glance

Sources/MainView.js
Sources/index.js
Sources/io/ReaderFactory.js
Sources/pv-explorer.mcss
package-lock.json

This adds a progress bar that tracks download progress when `openRemoteDataset` is called. One issue -- I have no idea where in the GUI it should go, any thoughts?

feat(download): Show download progress

---

Sources/io/ParaViewGlanceReaders.js
Sources/io/ReaderFactory.js

Pass in object descriptions of readers, and support passing in filename to a reader method.

Update registerReader api

---

Sources/layouts/Layout2D.js
Sources/layouts/Layout3D.js

Focus/activate a view when clicking in the render window container and slice sidebar.

fix(Layout): Activate views when clicked

---

Sources/index.js

fix(Glance): Correctly import registerReadersToProxyManager

---

Sources/MainView.js
Sources/config/glanceProxyConfig.js
Sources/io/ReaderFactory.js
Sources/layouts/Layout2D.js
Sources/layouts/Layout3D.js
Sources/layouts/LayoutQuad.js
Sources/layouts/LayoutSplit.js
package-lock.json
package.json

Fixes #23 
If there is any better way to specify which Layout component is active when switching between layouts, I'm all ears.

Proxy activation

---

Distribution/index.html
Documentation/config.js
Sources/externals/ITKReader/ITKImageReader.js
Sources/externals/ITKReader/index.js
Sources/externals/Workbox/index.js
Sources/externals/Workbox/serviceWorker.js
Utilities/helpers/externals.js
package-lock.json
package.json
webpack.config.js

WIP: Adds ITK reader support as well as Workbox support for caching
Issue reference: #3 
@thewtex @aylward 
To-do:
- When the ITK extensions are registered and listed, chrome thinks the page is in Vietnamese...

WIP ITK reader and workbox support

---

Sources/config/glanceLayoutConfig.js

Fixes regression where slices fail to sync between 2D and 3D views.

Fix layout config to sync views

---

Sources/index.js
Sources/io/ReaderFactory.js

Consolidates redundant code between the url loading and local file loading pathways.
This should fix your network-based dataset loading issues, @samuelgerber

Fix network dataset loading

---

Sources/index.js

fix(Entry): Pass reader through when downloading datasets

---

Sources/config/Generic/proxyUI.js
Sources/ui/Button/Button.mcss
Sources/ui/Button/index.js

Fixes regression regarding disappearing Geometry colormaps.
Removal of unused code in Button.

Misc fixes

---

Utilities/helpers/externals.js
package-lock.json
package.json

Fixes #58, and fixes externals building

Upgrade itkjs and vtkjs and fix externals building

---

Sources/MainView.js
Sources/controls/FileLoader/RawReader.js
Sources/controls/FileLoader/index.js
Sources/io/ReaderFactory.js
Sources/ui/Messages/Messages.mcss
Sources/ui/Messages/index.js
Sources/ui/index.js
package-lock.json
package.json

Notifies the user if a file load failed and provides links to both AdBlock issue and Glance's issue tracker. Closes #62

Tell user if file load errored

---

Sources/controls/FileLoader/index.js
Sources/ui/Progress/ProgressContainer.js
Sources/ui/Progress/ProgressContainer.mcss
Sources/ui/Progress/index.js

Show indeterminate progress when loading files, as large files do take some time.

Indeterminate progress

---

Sources/layouts/Layout2D.js

Reference: #16 (doesn't address the background colors yet)

fix(Layout2D): Use Slicer's slice view colors

---

package-lock.json
package.json
src/components/core/VtkView/script.js
src/vtkwidgets/CropWidget/index.js
src/vtkwidgets/WidgetManager/index.js

fix(WidgetManager): Support widget resets

---

README.md
build/webpack.base.config.js
package-lock.json
package.json

Docs have been updated to address #125
Dev server builds write built files to dist/ so workbox doesn't complain on first build.

Fix docs and dev server builds

---

src/components/core/App/script.js
src/components/core/App/template.html
src/components/core/Screenshots/script.js
src/components/core/Screenshots/style.css
src/components/core/Screenshots/template.html
src/components/core/VtkView/script.js
src/components/core/VtkView/style.css
src/stores/screenshots.js
src/stores/types.js

Add screenshot empty state filler

---

src/components/core/VtkView/script.js
src/config/proxy.js

- Use active source for crop target
- Activate sources when they are created

fix(VtkView): Remove crop widget when source is deleted

---

src/components/core/Screenshots/ScreenshotDialog/script.js

Screenshot fixes

---

src/components/core/Datasets/style.css

fix(Datasets): Truncate long dataset names

---

src/components/core/VtkView/style.css
src/stores/views.js

Background color fixes

---

src/components/core/BrowserIssues/script.js
src/components/core/BrowserIssues/template.html
src/components/core/VtkView/style.css

Fixes #149 and adjusts issue popup wording.

Fixes: browser issue wording, floating toolbar

---

build/writeVersion.js
documentation/app-override/index.html
documentation/content/doc/keyboard_shortcuts.md
package-lock.json
package.json
src/components/core/AboutBox/script.js
src/components/core/AboutBox/style.css
src/components/core/AboutBox/template.html
src/components/core/App/script.js
src/components/core/App/template.html
src/components/core/ErrorBox/script.js
src/samples/index.js
src/shortcuts.js
src/stores/fileLoader.js
src/stores/index.js
src/stores/screenshots.js
src/stores/types.js
static/index.html

Jumbo a lot of different commits

---

package-lock.json
package.json
src/stores/index.js

Using a custom merge implementation to make all recursively merged
properties reactive.

fix(stores): Background color wasn't reactive

---

package-lock.json
package.json
src/stores/fileLoader.js
src/stores/index.js

Provides clearer load errors when dataset fails to load on state restore.

fix(fileLoader): Provide clearer loading errors

---

src/components/core/AboutBox/template.html
src/components/core/App/script.js
src/components/core/App/style.css
src/components/core/App/template.html
src/components/core/BrowserIssues/template.html
src/components/core/ErrorBox/style.css
src/components/core/Landing/style.css
src/components/core/Landing/template.html
src/components/core/Screenshots/ScreenshotDialog/script.js
src/components/core/Screenshots/ScreenshotDialog/template.html
src/components/core/Screenshots/style.css
src/components/core/Screenshots/template.html
src/components/core/VtkView/script.js
src/components/core/VtkView/template.html
static/icons/paraview-glance-small.svg

Tweaks and changes to be more mobile-friendly. Needs testing feedback. You can test it here: http://forrestli.com/glance/
Outstanding issues:

Mobile friendly Glance

---

src/components/core/App/script.js
src/components/core/Landing/script.js
src/components/core/Landing/template.html
src/components/core/LayoutView/script.js
src/components/core/VtkView/script.js
src/constants.js

- restrict to only showing 1 view on mobile, regardless of state
- mobile breakpoint adjustments

Mobile tweaks

---

src/components/controls/ColorBy/template.html
src/components/core/ControlsDrawer/template.html

Also disable sidebar swiping when moving the piecewise function editor. Fixes #135

fix(ControlsDrawer): Disable tab swipe

---

src/app.js
src/components/core/App/style.css
src/components/core/App/template.html
static/global.css
static/index.html

Use fixed position on full page to more closely mimic a full-page mobile app.

fix(App): Confine app between addressbar and navbar

---

src/components/core/BrowserIssues/template.html
src/components/core/Landing/template.html
src/components/core/VtkView/constants.js

Fix misc issues

---

package-lock.json
package.json

Pulls in vtk.js fix for volume rendering

chore(vtkjs): Bump vtk.js to 7.8.4

---

externals/ITKReader/ITKDicomImageReader.js
externals/ITKReader/index.js
src/components/core/FileLoader/script.js
src/components/core/FileLoader/template.html
src/io/ReaderFactory.js
src/stores/fileLoader.js
src/stores/index.js
src/stores/types.js

- DICOM image loading via itk.js
- Refactored file loading to allow for reading images from ZIP files

Add DICOM image and zip container support

---

package-lock.json
package.json
src/components/core/Datasets/helper.js
src/config/proxyUI.js

Supports non-integer window width/level values
Fixes #217

fix(proxyUI): Window width/level deltas should be more granular

---

src/components/core/App/template.html
src/components/core/ErrorBox/template.html

Misc fixes and bump to 3.0

---

externals/ITKReader/ITKDicomImageReader.js
externals/ITKReader/index.js
src/io/ReaderFactory.js
src/stores/fileLoader.js

Also fix guard check on reader existence in ReaderFactory.

Fix dicom reader to merge dicom slices

---

package-lock.json
package.json
src/components/controls/ColorBy/script.js

DO NOT MERGE: depends on vtk.js PR https://github.com/Kitware/vtk-js/pull/947.
Restores the preset opacity shift slider when loading a glance state.

fix(ColorBy): Restore preset opacity shift

---

package-lock.json
package.json
src/components/controls/ColorBy/template.html
src/components/controls/Information/FieldData/template.html
src/components/controls/Information/ImageData/template.html
src/components/controls/Information/MatrixView/template.html
src/components/controls/Information/PolyData/template.html
src/components/controls/Information/template.html
src/components/controls/Molecule/template.html
src/components/controls/Representation/template.html
src/components/controls/SliceControl/template.html
src/components/controls/index.js
src/components/core/App/style.css
src/components/core/App/template.html
src/components/core/ControlsDrawer/index.vue
src/components/core/ControlsDrawer/style.css
src/components/core/ControlsDrawer/template.html
src/components/core/Datasets/script.js
src/components/core/Datasets/style.css
src/components/core/Datasets/template.html
src/components/core/FileLoader/template.html
src/components/core/Landing/template.html
src/components/core/RawFileReader/style.css
src/components/core/Screenshots/ScreenshotDialog/template.html
src/components/core/Screenshots/style.css
src/components/core/Screenshots/template.html
src/components/core/VtkView/style.css
src/components/widgets/PiecewiseFunctionEditor/style.css

Updates vuetify to 1.3.8 and tweaks styles to accommodate changes.

Vuetify upgrade + style tweak

---

src/components/core/ControlsDrawer/script.js
src/components/core/ControlsDrawer/template.html
src/components/core/EditTools/index.vue
src/components/core/EditTools/script.js
src/components/core/EditTools/template.html
src/components/core/VtkView/helper.js
src/components/core/VtkView/script.js
src/components/core/VtkView/template.html
src/components/tools/PaintTool/index.vue
src/components/tools/PaintTool/script.js
src/components/tools/PaintTool/style.css
src/components/tools/PaintTool/template.html
src/components/widgets/PalettePicker/template.html
src/components/widgets/PopUp/index.vue
src/components/widgets/PopUp/script.js
src/components/widgets/PopUp/style.css
src/components/widgets/PopUp/template.html
src/config/proxy.js
src/config/proxyViewRepresentationMapping.js
src/utils.js
src/vtk/LabelMap/index.js
src/vtk/LabelMapSliceRepProxy/index.js
src/vtk/LabelMapToImageFilter/index.js
src/vtk/LabelMapVolumeRepProxy/index.js

Adds painting to Glance. 
- painting labelmaps
- opacity for labelmaps
- undo/redo

feat(PaintTool): Add paint tool to Glance

---

package-lock.json
package.json
src/components/tools/PaintTool/script.js
src/components/tools/PaintTool/style.css
src/components/tools/PaintTool/template.html

- Fixes #237 
- Fixes #236
- Handle orientation was updating on active view change. Updating on
view StartMouseMove is more pleasant for the user. Fixes #239

Misc paint fixes

---

src/components/tools/CropTool/script.js
src/components/tools/CropTool/template.html
src/components/tools/MeasurementTools/script.js
src/components/tools/MeasurementTools/template.html
src/components/tools/PaintTool/script.js
src/components/tools/PaintTool/template.html
src/components/widgets/SourceSelect/index.vue
src/components/widgets/SourceSelect/script.js
src/components/widgets/SourceSelect/template.html
src/config/proxy.js
src/io/ReaderFactory.js
src/store/index.js

Use active source for crop, paint, and measurements.

Active source selection

---

src/components/core/Datasets/style.css
src/components/tools/CropTool/style.css
src/components/tools/CropTool/template.html
src/components/tools/MeasurementTools/script.js
src/components/tools/MeasurementTools/style.css
src/components/tools/MeasurementTools/template.html
src/components/tools/MeasurementTools/tools.js
src/components/tools/PaintTool/script.js
src/components/tools/PaintTool/style.css
src/components/tools/PaintTool/template.html
src/components/widgets/SourceSelect/script.js
src/components/widgets/SourceSelect/template.html
src/palette.js

Critiques welcome. Photo for reference:

Tools ui tweaks

---

src/components/tools/CropTool/script.js
src/components/tools/CropTool/template.html
src/components/tools/MeasurementTools/script.js
src/components/tools/MeasurementTools/template.html
src/vtk/CropWidget/behavior.js
src/vtk/CropWidget/index.js

See commit messages for a list of what has changed.

Tool tweaks

---

package-lock.json
package.json
src/components/tools/PaintTool/script.js
src/components/tools/PaintTool/template.html
src/components/widgets/SourceSelect/script.js

Bumps vtk.js to 11.4.2 to fix issue where crop widget bounds occasionally screw up.
Hides labelmap creation for now. The logic is buggy and needs to be rewritten.

Fix paint labelmap and crop widget

---

src/components/controls/ColorBy/script.js
src/components/controls/ColorBy/template.html
src/components/core/Datasets/style.css

Edit color mapping range for geometry.
@jourdain

fix(ColorBy): Make mapping range editable

---

externals/ITKReader/index.js
package-lock.json
package.json

Note: extensionToImageIO is now a JavaScript Map instead of an Object.

chore(Dependencies): Bump itk.js to 10.1.0

---

package-lock.json
package.json
src/app.js
src/components/core/App/script.js
src/components/core/App/template.html
src/components/core/FileLoader/script.js
src/components/core/FileLoader/style.css
src/components/core/FileLoader/template.html
src/components/core/Landing/script.js
src/components/core/RawFileReader/script.js
src/components/core/RawFileReader/template.html
src/io/ReaderFactory.js
src/store/fileLoader.js

This implements a new file loading dialog UX, which is designed to help integrate other data sources such as Girder (@HastingsGreer).
This is an initial draft, so comments and suggestions are welcome. You can view a build of it here (link is valid so long as this PR is active): https://paraview-glance-dev.netlify.com/
TODO:

New file loading dialog flow

---

package-lock.json
package.json

chore(vtk.js): Bump to 13.7.0

---

src/components/tools/CropTool/script.js
src/components/tools/MedianFilter/script.js
src/components/widgets/SourceSelect/script.js
src/components/widgets/SourceSelect/template.html

This generalizes the SourceSelect component to allow selecting of other types of sources, not just TrivialProducer.

fix(SourceSelect): Allow selection of more source types

---

externals/ITKReader/index.js
src/components/core/App/script.js
src/components/core/App/template.html
src/components/core/ControlsDrawer/template.html
src/components/core/FileLoader/script.js
src/components/core/FileLoader/template.html
src/components/core/GirderBox/script.js
src/components/core/VtkView/script.js
src/components/tools/MeasurementTools/script.js
src/components/tools/MeasurementTools/template.html
src/components/tools/MeasurementTools/tools/ToolTemplate2D.js
src/components/tools/MedianFilter/script.js
src/components/tools/PaintTool/script.js
src/components/tools/PaintTool/template.html
src/config/proxy.js
src/girder.js
src/io/ParaViewGlanceReaders.js
src/io/ReaderFactory.js
src/io/postProcessing.js
src/plugins.js
src/store/fileLoader.js
src/store/index.js
src/store/views.js

Added measurement upload and download
Added segmentation upload and download
Set default girder location to Stephen's covid dataset if logged out, users home if logged in

Girder Upload

---

package-lock.json
package.json
src/components/tools/MeasurementTools/script.js
src/components/tools/MeasurementTools/style.css
src/components/tools/MeasurementTools/template.html

- jump to measurement slice
- bump vtk.js version

Misc patches 3

---

src/components/core/Datasets/script.js
src/components/core/GirderBox/template.html
src/components/tools/MeasurementTools/script.js
src/components/tools/MeasurementTools/template.html
src/components/tools/PaintTool/script.js
src/components/tools/PaintTool/template.html

- toggle labelmap visibility
- hide girder box when uploading
- login warning
@aylward

Misc patches

---

package-lock.json
package.json

- Improved DICOM support (now based on GDCM).
- Improved IO performance.
@aylward @floryst @agirault

feat(IO): Bump itk.js to 12.2.0

---

src/components/core/App/script.js
src/components/core/App/template.html
src/components/core/GirderBox/script.js
src/io/postProcessing.js

- fix labelmap copy directions
- better upload notification ux
@aylward

Misc patches 6

---

documentation/config.js

Ref: https://discourse.paraview.org/t/paraview-glance-web-app-down/4199/2

chore(stable): Copy over correct stable index

---

static/index.html

fix(index.html): guard GA against non-prod builds

---

src/components/core/VtkView/script.js
src/components/core/VtkView/template.html

Views were not being mounted, since VtkView was being created before the
views were ready.
Should fix #329

fix(VtkView): Mount views when they are created

---

package-lock.json
package.json
src/store/index.js

Fix slicing step

---

src/config/proxyUI.js

This reverts commit 59e9816cf3a82fc8b0d821456fb6da31fe0cfde4.

Revert "style(config): Revert style change"

---

documentation/config.js
package-lock.json
package.json

Fix builds

---

package-lock.json
package.json
src/app.js
src/components/core/GirderBox/script.js
src/io/ReaderFactory.js
src/store/fileLoader.js
src/store/index.js
src/store/views.js

Send girder request token

---

package-lock.json
package.json
src/components/controls/ColorBy/script.js
src/components/controls/ColorBy/template.html
src/components/tools/PaintTool/script.js
src/config/proxy.js
src/config/proxyLinks.js
src/config/proxyUI.js
src/store/widgets.js
src/vtk/CustomSliceRepresentationProxy/index.js
src/vtk/CustomVolumeRepresentationProxy/index.js

Implements #351
This PR adds optional toggles to color 2D slices with the current colormap and/or the current opacity function.

Colorable slices

---

src/components/tools/PaintTool/script.js
src/components/tools/PaintTool/template.html

feat(PaintTool): Toggle 2D paintbrush

---

build/webpack.prod.config.js
package-lock.json
package.json

Bumps itk version and should fix paraview export (at least when using nightly).

Export fixes

---

src/components/controls/ColorBy/script.js
src/components/controls/ColorBy/template.html

Correctly set color range based on LUT rather than data array.
FYI @jourdain

Color range for vtkjs ParaView export

---

package-lock.json
package.json
src/vtk/CustomVolumeRepresentationProxy/index.js

See https://github.com/Kitware/vtk-js/pull/1605
@floryst

Use the slice mapper to render 2D volumes

---

src/io/GlanceVtkJsReader.js

Note: waiting on https://github.com/Kitware/vtk-js/pull/1629
This would allow Paraview-Glance to load .vtk-js files containg volumes that were exported from VTK or ParaView (see https://gitlab.kitware.com/vtk/vtk/-/merge_requests/7409 and https://gitlab.kitware.com/paraview/paraview/-/merge_requests/4531)

feat(GlanceVtkJsReader): Add support for volume import from .vtkjs

---

README.md

docs(README): Make prod deployment docs clearer

---

package.json
src/components/core/App/script.js
src/components/core/GlobalSettings/script.js
src/components/core/GlobalSettings/template.html
src/components/widgets/AnimationControls/index.vue
src/components/widgets/AnimationControls/script.js
src/components/widgets/AnimationControls/style.css
src/components/widgets/AnimationControls/template.html
src/config/proxy.js
src/io/GlanceVtkJsReader.js
src/store/animations.js
src/store/index.js

* Integrates the AnimationProxyManager into Paraview-Glance
* Adds animation controls to the global tab of the drawer

feat: Add animation controls

---

src/components/core/GlobalSettings/script.js
src/components/core/GlobalSettings/template.html
src/components/tools/MeasurementTools/tools/RulerMeasurementTool.js
src/components/tools/MeasurementTools/tools/ToolTemplate2D.js
src/store/widgets.js

feat(ruler): add global parameters for the ruler's unit symbol and factor

---

src/app.js

This adds a new setting `noHistory` to disable history routing for switching between landing/app.
In addition, we also now support setting properties in the URL parameters, e.g. `?setting.noHistory=true`.
Motivation: https://discourse.paraview.org/t/pvglance-iframe-back-button/7468

Add setting to disable history routing

---

src/components/core/Datasets/template.html

This allows ColorBy and other panels to execute any viz-changing actions.

fix(Datasets): Make panels load eagerly

---

.github/workflows/publish.yml
.github/workflows/verify.yml
build/writeVersion.js
documentation/config.js
package-lock.json
package.json

This is an attempt at migrating to github actions. We will see if this works.

Migrate to GitHub actions

---

package-lock.json
package.json

This PR updates the version of vtkjs to fix #428 
@floryst I hope this will do the trick.
Cheers
Rem

Update vtkjs version to latest release

---

build/webpack.base.config.js
package-lock.json
package.json

Hi @floryst do you mind if we push the latest changes to stable so that #429 is merged in?

Bump to stable

---

.github/workflows/publish.yml
README.md
build/webpack.prod.config.js
documentation/config.js
documentation/content/index.pug
documentation/tpl/__en__
src/components/core/App/script.js
src/components/core/App/template.html
src/store/fileLoader.js
src/store/index.js
static/redirect-app.html

- Reports progress when downloading datasets

Report progress

---

package-lock.json
package.json

chore: update vtk.js to v25

---

src/components/core/VtkView/script.js

fix(VtkView): force orientation axes visibility

---

.eslintrc.js
src/components/tools/MeasurementTools/tools/TextAnnotationTool.js
src/vtk/TextWidget/behavior.js
src/vtk/TextWidget/index.js

Part of the API of the widgets has changed in vtk.js making the widget crash.

fix(textwidget): Fix the TextWidget

---

src/store/fileLoader.js
src/store/index.js

This allows us to have a `"urls"` key on a dataset in a `state.json` in a `.glance` file. The files will be loaded and read as a file series.

feat(store): Support loading file series in restoreAppState

---

src/components/core/AboutBox/template.html

Removed reference to ParaView
Added links to vtk/web/Glance discourse category and github issue tracker.

AboutBox: Add link to community support and issue tracker

---

build/webpack.base.config.js

- Median filter files were not properly copied
- Apply prettier styling
Should close #470

fix(webpack): copy median filtering files

---

package-lock.json
package.json

bump VTK.js to v28.12.4
